# Site Settings
title: "AI Portfolio"
description: "Innovative AI Applications & Services"
theme: jekyll-theme-merlot
baseurl: ""

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# SEO settings
twitter:
  username: yourusername
  card: summary_large_image

social:
  name: Abdul wahab
  links:
    - https://github.com/aiprojectlab

# Analytics
google_analytics: UA-XXXXXXXXX-X

# Blog settings
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
